import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8f9fa' },
  content: { flex: 1, padding: 20, alignItems: 'center', justifyContent: 'center' },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  authContainer: { flex: 1, justifyContent: 'center', padding: 20, backgroundColor: '#f8f9fa' },
  authTitle: { fontSize: 42, fontWeight: 'bold', textAlign: 'center', marginBottom: 40, color: '#007AFF' },
  input: { backgroundColor: '#fff', paddingHorizontal: 15, paddingVertical: 12, borderRadius: 10, marginBottom: 15, borderWidth: 1, borderColor: '#ddd', fontSize: 16 },
  button: { backgroundColor: '#007AFF', padding: 15, borderRadius: 10, alignItems: 'center', width: '90%', marginTop: 20 },
  buttonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  buttonDisabled: { backgroundColor: '#a9a9a9' },
  link: { color: '#007AFF', textAlign: 'center', marginTop: 20, fontSize: 16 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingTop: 10, paddingBottom: 10, width: '100%' },
  welcomeText: { fontSize: 18, fontWeight: '500' },
  logoutText: { fontSize: 16, color: '#E53935', fontWeight: 'bold' },
  homeTitle: { fontSize: 48, fontWeight: 'bold', marginBottom: 40 },
  serviceButton: { width: '100%', padding: 20, backgroundColor: '#fff', borderRadius: 10, marginBottom: 15, borderWidth: 1, borderColor: '#ddd' },
  selectedService: { borderColor: '#007AFF', borderWidth: 2 },
  serviceText: { fontSize: 18, textAlign: 'center' },
  ticketCard: { width: '100%', backgroundColor: '#fff', borderRadius: 10, padding: 20, marginBottom: 15, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 5, elevation: 3 },
  ticketHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#eee', paddingBottom: 10, marginBottom: 10 },
  ticketService: { fontSize: 18, fontWeight: 'bold', color: '#007AFF' },
  ticketNumber: { fontSize: 16, fontWeight: 'bold', color: '#555' },
  ticketInfo: { fontSize: 16, color: '#333', marginBottom: 5 },
  dashboardContainer: { padding: 20 },
  dashboardTitle: { fontSize: 32, fontWeight: 'bold', marginBottom: 20 },
  statCard: { backgroundColor: '#fff', borderRadius: 10, padding: 20, marginBottom: 20, alignItems: 'center', shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 5, elevation: 3 },
  statLabel: { fontSize: 18, fontWeight: 'bold', marginBottom: 15, color: '#333', textAlign: 'center' },
});